services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d marketplace"]
      interval: 5s
      timeout: 5s
      retries: 10

  catalog-api:
    build:
      context: .. 
      dockerfile: services/catalog/src/Catalog.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=marketplace;Username=pguser;Password=pgpass
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  inventory-api:
    build:
      context: ..  
      dockerfile: services/inventory/src/Inventory.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=marketplace;Username=pguser;Password=pgpass
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata: